import type { ExportArticle, GenerateWxrOptions } from '../../types/domain';
import { cdata, cdataSafe, escapeXml, slugFromLink, slugify } from './xml';

function buildAuthorItems(articles: ExportArticle[]): string {
  const logins = new Map<string, number>();
  for (const article of articles) {
    if (article.authorLogin && !logins.has(article.authorLogin)) {
      logins.set(article.authorLogin, logins.size + 1);
    }
  }
  return Array.from(logins.entries())
    .map(
      ([login, id]) => `
	<wp:author>
		<wp:author_id>${id}</wp:author_id>
		${cdata('wp:author_login', login)}
		${cdata('wp:author_email', '')}
		${cdata('wp:author_display_name', login)}
		${cdata('wp:author_first_name', '')}
		${cdata('wp:author_last_name', '')}
	</wp:author>`,
    )
    .join('');
}

function buildTermXml(article: ExportArticle): string {
  return article.terms
    .map(
      (term) =>
        `\n\t\t<category domain="${escapeXml(term.domain)}" nicename="${escapeXml(term.nicename)}"><![CDATA[${cdataSafe(term.name)}]]></category>`,
    )
    .join('');
}

function buildArticleItem(article: ExportArticle): string {
  const postName = article.postName || slugFromLink(article.link) || slugify(article.title);
  const pubDate = article.postDate ? new Date(article.postDate).toUTCString() : new Date().toUTCString();

  return `
	<item>
		${cdata('title', article.title)}
		<link>${escapeXml(article.link)}</link>
		<pubDate>${pubDate}</pubDate>
		${cdata('dc:creator', article.authorLogin)}
		<guid isPermaLink="false">${escapeXml(article.link)}</guid>
		<description></description>
		<content:encoded><![CDATA[${cdataSafe(article.contentHtml)}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>${article.postId}</wp:post_id>
		${cdata('wp:post_date', article.postDate)}
		${cdata('wp:post_date_gmt', article.postDate)}
		${cdata('wp:comment_status', 'closed')}
		${cdata('wp:ping_status', 'closed')}
		${cdata('wp:post_name', postName)}
		${cdata('wp:status', 'publish')}
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		${cdata('wp:post_type', 'post')}
		${cdata('wp:post_password', '')}
		<wp:is_sticky>0</wp:is_sticky>${buildTermXml(article)}
	</item>`;
}

/** Emits a WXR (WordPress eXtended RSS) export: channel header, taxonomy
 * terms as per-item <category domain> elements, and one <item> per
 * article with CDATA-wrapped content. String-templated rather than built
 * with a generic XML serializer so CDATA payloads containing arbitrary
 * article text stay under direct control (see cdataSafe). */
export function generateWxr(articles: ExportArticle[], options: GenerateWxrOptions): string {
  const language = options.language ?? 'en-US';
  const authorItems = buildAuthorItems(articles);
  const articleItems = articles.map(buildArticleItem);

  return `<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Relay -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
	<title>${escapeXml(options.siteTitle)}</title>
	<link>${escapeXml(options.siteUrl)}</link>
	<description></description>
	<pubDate>${new Date().toUTCString()}</pubDate>
	<language>${language}</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>${escapeXml(options.siteUrl)}</wp:base_site_url>
	<wp:base_blog_url>${escapeXml(options.siteUrl)}</wp:base_blog_url>
${authorItems}
${articleItems.join('\n')}
</channel>
</rss>
`;
}
